$(document).ready(function(){
  $(".videolink").click(function(){
    $("#video").fadeIn();
  })
  $("#gwccalink").click(function(){
    $("#gwcca").fadeIn();
  })
  $(".closebtn").click(function(){
    $("#video").fadeOut();
    $("#gwcca").fadeOut();
  })
})
